
FROM alpine:3.15

RUN apk update && apk upgrade && apk add openrc mysql mysql-client && openrc && mysql_install_db --user=mysql --datadir=/var/lib/mysql

COPY tools/entrypoint.sh /

RUN chmod +x entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3306

STOPSIGNAL SIGQUIT

CMD ["mysqld_safe"]
