
FROM alpine:3.15

RUN apk update && apk upgrade && apk add mysql mysql-client

COPY tools/entrypoint.sh /

COPY ./conf/my.cnf /etc/mysql/

RUN chmod +x entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3306

STOPSIGNAL SIGQUIT

CMD ["mysqld_safe"]
