
FROM alpine:3.15

RUN apk update && apk upgrade && apk add php7 php-mysqli php7-fpm php7-phar php7-mbstring php-json wget

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && wp core download --allow-root; \ 
		adduser -S nginx \ 
		&& addgroup -S nginx

COPY wp-config.php  /var/www/

COPY www.conf /etc/php7/php-fpm.d

COPY tools/wordpress.sh /

RUN chmod +x /wordpress.sh
EXPOSE 9000


ENTRYPOINT ["/wordpress.sh"]


