
FROM alpine:3.15

RUN apk update && apk upgrade && apk add php7 php-mysqli php7-fpm php7-phar php-json wget

RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp && wp core download --allow-root;

COPY wp-config.php  /

EXPOSE 9000


